name: vd_cenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - librosa
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - numpy=1.26.4
  - pip
  - pip:
      - transformers
      - soundfile
      - openai-whisper
      - gradio
      - python-dotenv
      - torch --index-url https://download.pytorch.org/whl/nightly/cu128
      - torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

  - torch
  - torchaudio